import { Component } from '@angular/core'; import { NgFor } from '@angular/common'; import { RouterLink } from '@angular/router';
@Component({selector:'app-projects',standalone:true,imports:[NgFor,RouterLink],template:`
<section class="page-hero"><div class="section-tag reveal">PROJECTS / SELECTED BUILDS</div><h1 class="reveal">Work that makes<br><span>ideas visible.</span></h1><p class="reveal">A showcase of the kind of digital products, systems and brand experiences FEKRA can create.</p></section>
<section class="projects section"><article class="case reveal" *ngFor="let p of projects;let i=index"><div class="case-visual" [class]="p.cls"><div class="case-glow"></div><div class="case-inner"><span>{{p.category}}</span><strong>{{p.visual}}</strong><small>{{p.stack}}</small></div></div><div class="case-copy"><div class="section-tag">0{{i+1}} / {{p.category}}</div><h2>{{p.title}}</h2><p>{{p.desc}}</p><div class="tag-row"><span *ngFor="let x of p.tags">{{x}}</span></div></div></article></section>
<section class="project-note section reveal"><div><div class="section-tag">MORE THAN A SHOWCASE</div><h2>Your project can be the next <span>case study.</span></h2></div><p>FEKRA is built to handle different project shapes: public websites, mobile products, operational systems, design work, academic software and digital invitations.</p></section>
<section class="cta-band compact"><div class="section-tag">YOUR PROJECT COULD BE NEXT</div><h2>Let's make it<br><span>worth showing.</span></h2><a class="btn light" routerLink="/contact">Start a project ↗</a></section>`})
export class ProjectsComponent { projects=[
{title:'Luna Accessories',category:'WEB / E-COMMERCE',visual:'LUNA / SHOP',stack:'Angular • Firebase',desc:'A polished accessories storefront direction focused on product presentation, responsive browsing and a memorable brand identity.',tags:['E-commerce','Angular','Branding'],cls:'case-purple'},
{title:'Gym Management Platform',category:'MOBILE / MANAGEMENT',visual:'GYM / CONTROL',stack:'Flutter • Firebase • BLoC',desc:'A mobile management experience designed for day-to-day gym operations, with a structured architecture and connected backend services.',tags:['Flutter','Firebase','Management'],cls:'case-dark'},
{title:'Fruit Hub',category:'MOBILE / E-COMMERCE',visual:'FRUIT / SHOP',stack:'Flutter • Supabase • APIs',desc:'An e-commerce mobile concept for discovering products and moving through a clean shopping journey.',tags:['Mobile','E-commerce','APIs'],cls:'case-light'},
{title:'ElZainhom',category:'WEB / BUSINESS SYSTEM',visual:'BUSINESS / GROW',stack:'Angular • .NET • APIs',desc:'A business website and management direction combining customer information, product categories, contact flows and an admin experience.',tags:['Angular','.NET','Admin Panel'],cls:'case-purple'}
]; }
