import { Component } from '@angular/core';
import { NgFor } from '@angular/common';
import { RouterLink } from '@angular/router';
import { LanguageService } from '../services/language.service';

@Component({
  selector:'app-services', standalone:true, imports:[NgFor, RouterLink],
  template:`
    <section class="page-hero"><div class="page-hero-orb"></div><div class="section-tag reveal">{{ ar ? 'الخدمات / ماذا نقدم' : 'SERVICES / WHAT WE DO' }}</div><h1 class="reveal">{{ ar ? 'منظومة رقمية' : 'A full digital' }}<br><span>{{ ar ? 'متكاملة.' : 'capability stack.' }}</span></h1><p class="reveal">{{ ar ? 'مجالات متعددة وإمكانيات متنوعة وهدف واحد: بناء الحل الرقمي المناسب لمشروعك.' : 'Seven service capabilities, dozens of options, and one goal: build the right digital solution for the job.' }}</p></section>
    <section class="services-list section">
      <article *ngFor="let s of services;let i=index" class="big-service reveal" [style.--delay.ms]="i * 80">
        <div class="big-num">0{{i+1}}</div><div class="big-icon">{{s.icon}}</div><div class="big-copy"><div class="service-label">{{s.label}}</div><h2>{{ ar ? s.arTitle : s.title }}</h2><p>{{ ar ? s.arText : s.text }}</p><div class="tag-row"><span *ngFor="let x of (ar ? s.arTags : s.tags)">{{x}}</span></div></div><div class="arrow">↗</div>
      </article>
    </section>
    <section class="service-bottom section"><div class="service-bottom-copy reveal-left"><div class="section-tag">{{ ar ? 'مصمم حول احتياجات مشروعك' : 'BUILT AROUND YOUR BUSINESS' }}</div><h2>{{ ar ? 'كل مشروع يحتاج' : 'Not every business needs the same' }} <span>{{ ar ? 'حلًا مناسبًا.' : 'solution.' }}</span></h2><p>{{ ar ? 'فكرا لا تقدم قالبًا واحدًا للجميع. ندمج قدراتنا حسب المشروع: موقع مع لوحة تحكم، تطبيق متصل بواجهات API، منصة إلكترونية، نظام POS، دعوة تفاعلية أو حضور مهني شخصي.' : 'FEKRA does not sell one fixed template. We combine the capabilities above according to the project: a website with a dashboard, an app connected to APIs, an electronic platform, a complete POS, an interactive invitation or a personal career presence.' }}</p></div><div class="capability-wheel scale-in"><span>IDEA</span><i></i><span>DESIGN</span><i></i><span>BUILD</span><i></i><span>LAUNCH</span></div></section>
    <section class="cta-band compact"><div class="section-tag">{{ ar ? 'جاهز نبدأ؟' : 'READY WHEN YOU ARE' }}</div><h2>{{ ar ? 'هات فكرة' : 'Bring the' }} <span>{{ ar ? 'فكرتك.' : 'Fekra.' }}</span></h2><a class="btn light" routerLink="/contact">{{ ar ? 'احكيلنا عنها' : 'Tell us about it' }} ↗</a></section>
  `
})
export class ServicesComponent {
  get ar(): boolean { return this.languageService.isArabic(); }
  constructor(private languageService: LanguageService) {}

  services = [
    {icon:'◫',label:'01 / WEB',title:'Web Development',arTitle:'تطوير المواقع والمنصات',text:'Complete web experiences from a focused landing page to a full business platform.',arText:'تجارب ويب متكاملة تبدأ من صفحة هبوط وتصل إلى منصة إلكترونية أو نظام أعمال كامل.',tags:['Websites','Landing Pages','E-commerce','Electronic Platforms','Dashboards','Admin Panels','Web Applications','Booking Systems','Corporate / Restaurant / Clinic Sites'],arTags:['مواقع','Landing Pages','متاجر إلكترونية','منصات إلكترونية','لوحات تحكم','لوحات إدارة','تطبيقات ويب','أنظمة حجز','مواقع شركات ومطاعم وعيادات']},
    {icon:'⌁',label:'02 / MOBILE',title:'Mobile App Development',arTitle:'تطوير تطبيقات الموبايل',text:'Cross-platform products for Android and iOS with the integrations your app needs.',arText:'تطبيقات Android وiOS باستخدام Flutter مع التكاملات والـAPIs التي يحتاجها مشروعك.',tags:['Android','iOS','Flutter Apps','Store Apps','Service Apps','Booking Apps','REST APIs','Firebase'],arTags:['Android','iOS','Flutter','تطبيقات المتاجر','تطبيقات الخدمات','تطبيقات الحجز','REST APIs','Firebase']},
    {icon:'▱',label:'03 / SYSTEMS',title:'Software Systems',arTitle:'الأنظمة البرمجية',text:'Custom internal and customer-facing systems designed around how your business actually works.',arText:'أنظمة مخصصة لإدارة وتشغيل الأعمال ومصممة حسب طريقة عمل مشروعك.',tags:['Management','POS','Inventory','HR','Booking','CRM','School / Academy','Restaurant','Dashboards','Custom Business Systems'],arTags:['إدارة','POS','مخازن','موارد بشرية','حجز','CRM','مدارس وأكاديميات','مطاعم','لوحات تحكم','أنظمة مخصصة']},
    {icon:'✦',label:'04 / DESIGN',title:'UI/UX & Branding',arTitle:'UI/UX والهوية البصرية',text:'A visual and product language that makes your business easier to understand and remember.',arText:'تصميم بصري وتجربة استخدام تساعد جمهورك يفهم مشروعك ويفتكره.',tags:['UI/UX','Website Design','Mobile App Design','Logo Design','Brand Identity','Social Media Design','Design Systems'],arTags:['UI/UX','تصميم مواقع','تصميم تطبيقات','تصميم لوجو','هوية بصرية','تصميم سوشيال ميديا','Design Systems']},
    {icon:'⌘',label:'05 / ACADEMIC',title:'Academic Project Development & Support',arTitle:'تطوير ودعم المشروعات الأكاديمية',text:'Professional software project development and preparation presented as structured academic support.',arText:'تطوير وتجهيز مشروعات التخرج والمشروعات الجامعية مع التوثيق والشرح والتحضير.',tags:['Graduation Projects','University Projects','Software Projects','Flutter Projects','Web Projects','Documentation','Presentations','UML / ERD / Use Case','Project Explanation'],arTags:['مشروعات تخرج','مشروعات جامعية','مشروعات برمجية','Flutter','Web','Documentation','Presentations','UML / ERD / Use Case','شرح المشروع']},
    {icon:'↗',label:'06 / CAREER',title:'Career Services',arTitle:'خدمات المسار المهني',text:'A stronger digital presence for students and professionals preparing for the next opportunity.',arText:'نساعد الطلاب والمحترفين في بناء حضور مهني أقوى والاستعداد للفرصة القادمة.',tags:['ATS-Friendly CV','CV Design','Portfolio','LinkedIn Profile','Personal Website','Cover Letter','Resume Optimization'],arTags:['CV متوافق مع ATS','تصميم CV','Portfolio','LinkedIn','موقع شخصي','Cover Letter','تحسين السيرة الذاتية']},
    {icon:'♡',label:'07 / INVITATIONS',title:'Digital Invitations',arTitle:'الدعوات الرقمية',text:'Interactive invitations that feel like a real digital experience rather than a static image.',arText:'دعوات تفاعلية تبدو كتجربة رقمية متكاملة وليست مجرد صورة ثابتة.',tags:['Wedding','Engagement','Birthday','Graduation','Baby Shower','Events','Music','Photos','Location','Countdown','RSVP','Google Maps'],arTags:['زفاف','خطوبة','عيد ميلاد','تخرج','بيبي شاور','فعاليات','موسيقى','صور','موقع','عد تنازلي','RSVP','Google Maps']}
  ];
}
